services:
  app:
    image: gradle:jdk23-alpine
    working_dir: /app
    volumes:
      - gradle-build:/app/build
      - gradle-cache:/app/.gradle
      - ./build.gradle:/app/build.gradle
      - ./src:/app/src
      - ./statics:/app/statics
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: gradle --no-daemon run
volumes:
  gradle-build:
  gradle-cache: